config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, skip: [:registrations]
  
  get 'reload_seed', to: 'home#reload_seed', as: :reload
  resources :people
  resources :movies

  namespace :api, defaults: { format: 'json' } do
    namespace :v1, defaults: { format: 'json' } do
      get 'movies' => 'movies#index'
      get 'movies/:id' => 'movies#show'

      get 'people' => 'people#index'
      get 'people/:id' => 'people#show'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  paginates_per 5

  validates :title, :release_year, presence: true
  validates :release_year, numericality: true

  has_many :movies_person
  has_many :people, through: :movies_person, source: :person, dependent: :destroy

  ROMAN_NUMS = {
    'M' => 1000,
    'CM' => 900,
    'D' => 500,
    'CD' => 400,
    'C' => 100,
    'XC' => 90,
    'L' => 50,
    'XL' => 40,
    'X' => 10,
    'IX' => 9,
    'V' => 5,
    'IV' => 4,
    'I' => 1
  }

  def self.romanize(num)
    ROMAN_NUMS.map do |ltr, val|
      amt, num = num.divmod(val)
      ltr * amt
    end.join
  end

  def directors
    staff_with_role('director')
  end

  def producers
    staff_with_role('producer')
  end

  def casting
    staff_with_role('actor')
  end

  private

  def staff_with_role(role)
    people.where('movies_people.role = ?', role)
  end
end

app/models/movies_person.rb
class MoviesPerson < ApplicationRecord
  belongs_to :person
  belongs_to :movie

  validates :movie_id, :person_id, :role, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  paginates_per 5
  
  validates :last_name, :first_name, :aliases, presence: true

  has_many :movies_person
  has_many :movies, through: :movies_person, source: :movie, dependent: :destroy

  def as_director
    role_as('director')
  end

  def as_producer
    role_as('producer')
  end

  def as_actor
    role_as('actor')
  end

  private

  def role_as(role)
    movies.where('movies_people.role = ?', role)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/movies_controller.rb
class Api::V1::MoviesController < ApplicationController
  def index
    @movies = Movie.all
    render json: @movies
  end

  def show
    @movie = Movie.find params[:id]
    render json: @movie
  end
end

app/controllers/api/v1/people_controller.rb
class Api::V1::PeopleController < ApplicationController
  def index
    @people = Person.all
    render json: @people
  end

  def show
    @person = Person.find(params[:id])
    render json: @person
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  layout 'application'

  def index;  end

  def reload_seed
    Rails.application.load_seed
    redirect_to root_path
  end
end

app/controllers/movies_controller.rb
class MoviesController < ActionController::Base
  layout 'application'
  before_action :current_year, only: %i[new edit update create]
  before_action :people, only: %i[new edit update create]
  before_action :movie, only: %i[edit update destroy]
  before_action :staff, only: %i[edit update]

  def index
    @movies = Movie.order(:title).page params[:page]
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movies_params)

    respond_to do |format|
      if @movie.save
        StaffService.new(@movie, params).call
        format.html { redirect_to movies_path, notice: 'Movie was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @movie.update_attributes(movies_params)
        StaffService.new(@movie, params).call
        format.html { redirect_to movies_path, notice: 'Movie was successfully updated.' }
      else
        format.html { render action: :edit }
      end
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_url
  end

  private

  def staff
    @directors = @movie.directors.pluck(:id)
    @producers = @movie.producers.pluck(:id)
    @casting = @movie.casting.pluck(:id)
  end

  def movie
    @movie = Movie.find(params[:id])
  end

  def current_year
    @current_year = Date.today.year
  end

  def people
    @people = Person.all
  end

  def movies_params
    params.require(:movie).permit(:title,
                                  :release_year,
                                  producers: [],
                                  directors: [],
                                  casting: [])
  end
end

app/controllers/people_controller.rb
class PeopleController < ActionController::Base
  layout 'application'
  before_action :person, only: %i[edit update destroy]

  def index
    @people = Person.order(:first_name, :last_name).page params[:page]
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to people_path, notice: 'Person was successfully created.' }
      else
        format.html { render action: :new }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @person.update_attributes(person_params)
        format.html { redirect_to people_path, notice: 'Ad was successfully updated.' }
      else
        format.html { render action: :edit }
      end
    end
  end

  def destroy
    @person.destroy
    redirect_to people_url
  end

  private

  def person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:first_name,
                                   :last_name,
                                   :aliases)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1.mt-5 Movies Staff
%ul.list-unstyled
  %li People in different roles
  %li Movies info
- if current_user
  = link_to 'Reload Data', reload_path, data: { confirm: 'This will reset all data in db about Movies, People and Staff.. Are you sure?' }, class: "btn btn-warning btn-lg"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Moviesstaff
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    / Navigation
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.static-top
      .container
        %a.navbar-brand{href: "#"} Movies Staff
        %button.navbar-toggler{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", type: "button"}
          %span.navbar-toggler-icon
        #navbarResponsive.collapse.navbar-collapse
          %ul.navbar-nav.ml-auto
            - if current_user
              %li.nav-item.active
                %a.nav-link{href: "/"}
                  Home
                  %span.sr-only (current)
              %li.nav-item
                %a.nav-link{href: "/people"} People
              %li.nav-item
                %a.nav-link{href: "/movies"} Movies
            %li.nav-item
              - if current_user
                %a.nav-link{href: "/users/sign_out"} Logout
              - else
                %a.nav-link{href: "/users/sign_in"} Login
    / Page Content
    .container
      .row
        .col-lg-12
          = yield

app/views/movies/_form.html.haml
= form_for(@movie) do |f|
  = render partial: 'shared/errors', locals: {obj: @movie}
  .form-row
    .form-group.col-md-6
      %label{for: "title"} Title
      = f.text_field :title, class: "form-control", placeholder: "Title"
    .form-group.col-md-4
      %label{for: "inputState"} Release Year
      %select.form-control{id: "movie[release_year]", name: "movie[release_year]"}
        %option= @current_year
        - (1950..@current_year).each do |year|
          - selected = year == @movie.release_year ? true : false
          %option{value: "#{year}", selected: selected}
            = year
  .form-row
    = render partial: 'people', locals: {movie: @movie, people: @people, staff: @directors, role: 'directors'}
    = render partial: 'people', locals: {movie: @movie, people: @people, staff: @producers, role: 'producers'}
    = render partial: 'people', locals: {movie: @movie, people: @people, staff: @casting, role: 'casting'}
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/movies/_people.html.erb
<div class="form-group col-md-4">
  <label for="title"><%= role.titleize %></label>
  <select name="<%= role %>[]" class="mdb-select md-form colorful-select dropdown-primary custom-select" multiple searchable="Search here..">
    <%= people.each do |person| %>
      <% unless movie.new_record? %>
        <% selected = staff.include?(person.id) ? 'selected' : '' %>
      <% end %>
      <option value="<%= person.id %>" <%= selected %>><%= person.first_name %></option>
    <% end %>
  </select>
</div>

app/views/movies/_people.html.haml
.form-group.col-md-4
  %label{for: "title"}= role.titleize
  %select{name: ""}
  = role[]
    class="mdb-select md-form colorful-select dropdown-primary custom-select" multiple searchable="Search here.."&gt;
  \#{people.each do |person|}
    - unless movie.new_record?
      - selected = staff.include?(person.id) ? 'selected' : ''
    %option{value: ""}
    = person.id
    " #{selected}&gt;#{person.first_name}

app/views/movies/edit.html.haml
= link_to 'Back', movies_path, class: 'btn btn-secondary'
%hr/
%h1 Edit
= render partial: 'form', locals: {directors: @directors, producers: @producers, casting: @casting}

app/views/movies/index.html.haml
= link_to 'Add Movie', new_movie_path, class: "btn btn-primary btn-lg"
%hr/
.container.pagination.justify-content-center
  = paginate @movies, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm"
%table.table
  %thead
    %tr
      %th{scope: "col"} Title
      %th{scope: "col"} Release year
      %th{scope: "col"} Actions
  %tbody
    - @movies.each do |movie|
      %tr
        %th{scope: "row"}
          = movie[:title]
        %td
          = Movie.romanize(movie[:release_year])
        %td
          = link_to 'Edit Movie', edit_movie_path(movie), class: "btn btn-secondary"
          = link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
.container.pagination.justify-content-center
  = paginate @movies, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm"

app/views/movies/new.html.haml
= link_to 'Back', movies_path, class: 'btn btn-secondary'
%hr

= render partial: 'form'

app/views/people/_form.html.haml
= form_for(@person) do |f|
  = render partial: 'shared/errors', locals: {obj: @person}
  .form-row
    .form-group.col-md-6
      %label{for: "first_name"} First Name
      = f.text_field :first_name, class: "form-control", placeholder: "First name"
    .form-group.col-md-6
      %label{for: "last_name"} Last Name
      = f.text_field :last_name, class: "form-control", placeholder: "Last name"
    .form-group.col-md-6
      %label{for: "aliases"} Aliases
      = f.text_field :aliases, class: "form-control", placeholder: "Aliases"
  .actions
    = f.submit "Save", class: 'btn btn-primary'

app/views/people/edit.html.haml
= link_to 'Back', people_path, class: 'btn btn-secondary'
%hr/
%h1 Edit person
= render 'form'

app/views/people/index.html.haml
= link_to 'Add Person', new_person_path, class: "btn btn-primary btn-lg"
%hr/
.container.pagination.justify-content-center
  = paginate @people, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm"
%table.table
  %thead
    %tr
      %th{scope: "col"} First name
      %th{scope: "col"} Last name
      %th{scope: "col"} Aliases
      %th{scope: "col"} Actions
  %tbody
    - @people.each do |person|
      %tr
        %td
          = person.first_name
        %td
          = person.last_name
        %td
          = person.aliases
        %td
          = link_to 'Edit Person', edit_person_path(person), class: "btn btn-secondary"
          = link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
.container.pagination.justify-content-center
  = paginate @people, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm"

app/views/people/new.html.haml
= link_to 'Back', people_path, class: 'btn btn-secondary'
%hr/
%h1 New person
= render 'form'

app/views/shared/_errors.html.haml
- if obj.errors.any?
  #error_explanation.p-3.mb-2.bg-danger.text-white
    %p
      = pluralize(obj.errors.count, "error")
      prohibited this ad from being saved:
    %ul
      - obj.errors.full_messages.each do |msg|
        %li= msg